version: "3"

services:
  whatsapp-otp:
    build: .
    container_name: whatsapp-otp
    restart: unless-stopped
    ports:
      - "3002:3002"
    volumes:
      - ./wwebjs_auth:/usr/src/app/.wwebjs_auth
    environment:
      - NODE_ENV=production
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
    command: node server.js
